com:
 deploygate:
  gradle:
   url: 'http://repo1.maven.org/maven2'
  sdk:
   url: 'http://repo1.maven.org/maven2'
 bluepapa32:
  gradle:
   plugins:
    gradle-native2ascii-plugin:
     url: 'http://bluepapa32.github.io/maven'

